In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

csv_data_path=os.getenv("impact_data_dataframe_path")

shpfile_path=os.getenv("impact_data_dataframe_path")

In [2]:
import pandas as pd
import numpy as np
import re


em_data_filepath='emdat_public_2022_08_11_query_uid-IKGfZc.xlsx'
impact_events_filepath=f'{csv_data_path}impactevents-202408.xlsx'
dfb = pd.read_excel(em_data_filepath, engine='openpyxl',skiprows=6,sheet_name = 'emdat data')



flood_grp=['Flood']

#dfb1_ea=dfb1[dfb1['Country'].str.contains(ea_cntr)]
dfb_fl=dfb[dfb['Disaster Type'].isin(flood_grp)]

ea_cntr=['Djibouti', 'Eritrea','Ethiopia','Kenya','Rwanda', 'Somalia','South Sudan','Sudan (the)','Tanzania, United Republic of']

#dfb1_ea=dfb1[dfb1['Country'].str.contains(ea_cntr)]
dfb_fl_ea=dfb_fl[dfb_fl['Country'].isin(ea_cntr)]
#dfb_fl_ea.info()
dfb_fl_ea_map=dfb_fl_ea[['Dis No','Year','Country','ISO','Location']]
dfb_fl_ea_map['loc_str1'] = dfb_fl_ea_map['Location'].str.replace(' and ',',')
dfb_fl_ea_map['loc_str2'] = dfb_fl_ea_map['loc_str1'].str.replace(' & ',',')
dfb_fl_ea_map['loc_str3'] = dfb_fl_ea_map['loc_str2'].str.replace('&',',')
dfb_fl_ea_map['loc_str4'] = dfb_fl_ea_map['loc_str3'].str.replace(';',',')

dfb_fl_ea_map['loc_list'] = dfb_fl_ea_map['loc_str4'].str.split(',')
df_fl=dfb_fl_ea_map.explode('loc_list')
df_fl['row_idx']=np.core.defchararray.add('fl_', np.arange(0,len(df_fl.index),1).astype(str))

#df1_fl['loc_list_a'] = df1_fl['loc_list'].str.replace(r' \s', '', regex=True)
df1_fl=df_fl[['Dis No','Year','Country','ISO','loc_list','Location','row_idx']]
df2_fl=df1_fl.reset_index()

for idx,row in df2_fl.iterrows():
    #space_rmvd_str=re.sub(r"^\s", '', str(row['loc_list_a']), flags=re.IGNORECASE)
    #print(space_rmvd_str,row['loc_list_a'])
    df2_fl.loc[idx,'loc_list_a']= re.sub(r"^\s", '', str(row['loc_list']), flags=re.IGNORECASE)
    
df3_fl=df2_fl[['Dis No','Year','Country','ISO','loc_list','loc_list_a','Location','row_idx']]

#df3_fl.to_csv(f'{csv_data_path}ea_flood_location.csv',index=False)
#d
#df3_fl.info()


# db=pd.read_csv(f'{csv_data_path}ea_flood_missing_location.csv')

# db['code']=db['Dis No'].str.split('-').str[-1]

# db['loc_list'] = db['Location'].str.split(',')
# db1=db.explode('loc_list')
# #db2=db1.drop_duplicates('loc_list')

# db2=db1.drop_duplicates('code')
# code_list=db2['code'].tolist()
# db1.to_csv(f'{csv_data_path}ea_flood_missing_location_v1.csv')

/nix/store/4w5a1nh3y7gcbr9xw00ir2yipykbabra-python3.9-openpyxl-3.0.7/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
<ipython-input-2-289789446a02>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str1'] = dfb_fl_ea_map['Location'].str.replace(' and ',',')
<ipython-input-2-289789446a02>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str2'] = dfb_fl_ea_map['loc_str1'].str.replace(' & ',',')
<ipython-input-2-289789446a02>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str3'] = dfb_fl_ea_map['loc_str2'].str.replace('&',',')
<ipython-input-2-289789446a02>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_str4'] = dfb_fl_ea_map['loc_str3'].str.replace(';',',')
<ipython-input-2-289789446a02>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_map['loc_list'] = dfb_fl_ea_map['loc_str4'].str.split(',')

In [3]:
dfb_fl_ea.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 269 entries, 33 to 4631
Data columns (total 50 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Dis No                                     269 non-null    object
 1   Year                                       269 non-null    int64
 2   Seq                                        269 non-null    int64
 3   Glide                                      53 non-null     object
 4   Disaster Group                             269 non-null    object
 5   Disaster Subgroup                          269 non-null    object
 6   Disaster Type                              269 non-null    object
 7   Disaster Subtype                           204 non-null    object
 8   Disaster Subsubtype                        0 non-null      object
 9   Event Name                                 0 non-null      object
 10  Country                                    269 non-null    object
 11  ISO                                        269 non-null    object
 12  Region                                     269 non-null    object
 13  Continent                                  269 non-null    object
 14  Location                                   265 non-null    object
 15  Origin                                     190 non-null    object
 16  Associated Dis                             48 non-null     object
 17  Associated Dis2                            6 non-null      object
 18  OFDA Response                              15 non-null     object
 19  Appeal                                     24 non-null     object
 20  Declaration                                24 non-null     object
 21  Aid Contribution                           21 non-null     float64
 22  Dis Mag Value                              104 non-null    float64
 23  Dis Mag Scale                              269 non-null    object
 24  Latitude                                   75 non-null     object
 25  Longitude                                  75 non-null     object
 26  Local Time                                 0 non-null      object
 27  River Basin                                93 non-null     object
 28  Start Year                                 269 non-null    int64
 29  Start Month                                269 non-null    float64
 30  Start Day                                  240 non-null    float64
 31  End Year                                   269 non-null    int64
 32  End Month                                  269 non-null    float64
 33  End Day                                    244 non-null    float64
 34  Total Deaths                               201 non-null    float64
 35  No Injured                                 45 non-null     float64
 36  No Affected                                201 non-null    float64
 37  No Homeless                                55 non-null     float64
 38  Total Affected                             239 non-null    float64
 39  Reconstruction Costs ('000 US$)            2 non-null      float64
 40  Reconstruction Costs, Adjusted ('000 US$)  2 non-null      float64
 41  Insured Damages ('000 US$)                 1 non-null      float64
 42  Insured Damages, Adjusted ('000 US$)       1 non-null      float64
 43  Total Damages ('000 US$)                   31 non-null     float64
 44  Total Damages, Adjusted ('000 US$)         31 non-null     float64
 45  CPI                                        264 non-null    float64
 46  Adm Level                                  215 non-null    object
 47  Admin1 Code                                99 non-null     object
 48  Admin2 Code                                138 non-null    object
 49  Geo Locations                              215 non-null    object
dtypes: float64(18), int64(4), object(28)
memory usage: 107.2+ KB

In [4]:
csv_data_path='data/'
db=pd.read_csv(f'{csv_data_path}ea_flood_missing_location.csv')

db['code']=db['Dis No'].str.split('-').str[-1]

db['loc_list'] = db['Location'].str.split(',')
db1=db.explode('loc_list')
#db2=db1.drop_duplicates('loc_list')

db2=db1.drop_duplicates('code')
code_list=db2['code'].tolist()
#db1.to_csv(f'{csv_data_path}ea_flood_missing_location_v1.csv')

In [5]:
db2

,Dis No,Location,code,loc_list
0,1993-0005-TZA,"Lushoto, Korogwe districts (Tanga region)",TZA,Lushoto
3,1994-0507-DJI,"Djibouti city, Holhol, Ali Addeh, Tadjoura dis...",DJI,Djibouti city
4,1994-0194-ETH,"North Shoa, South Welo, Tach Gayint district (...",ETH,North Shoa
8,1996-0474-KEN,Nyanza province,KEN,Nyanza province
12,1994-0217-SDN,"El Fasher, Nyala (Darfur state), Hamrat El Wiz...",SDN,El Fasher
13,1994-0573-SOM,South,SOM,South

In [6]:
import geopandas as gp

shpfile_path='data/'
gaul_adm2=gp.read_file(f'{shpfile_path}ea_adm2_gaul.shp')

In [7]:
gaul_adm2

                                               geometry
0     MULTIPOLYGON (((43.45552 15.97692, 43.45554 15...
1     POLYGON ((23.28750 8.76171, 23.28112 8.75005, ...
2     POLYGON ((24.27220 8.27699, 24.27390 8.27343, ...
3     POLYGON ((44.26976 14.20502, 44.26981 14.20496...
4     POLYGON ((43.54572 15.97740, 43.55705 15.97485...
...                                                 ...
1449  POLYGON ((43.22042 16.18735, 43.22144 16.18402...
1450  POLYGON ((43.44169 15.98401, 43.44304 15.98109...
1451  POLYGON ((43.43349 16.07773, 43.43851 16.07462...
1452  POLYGON ((43.57590 16.09728, 43.57911 16.09281...
1453  POLYGON ((43.70865 15.93842, 43.70853 15.93832...

[1454 rows x 1 columns]

In [8]:
import geopandas as gp
import pandas as pd

adm0=gp.read_file(f'{shpfile_path}ea_adm0_geoboundaries.shp')
adm1=gp.read_file(f'{shpfile_path}ea_adm1_geoboundaries.shp')
adm2=gp.read_file(f'{shpfile_path}ea_adm2_geoboundaries.shp')

db=pd.concat([adm0,adm1,adm2])

db1=db.drop_duplicates('shapeID')
db1.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Int64Index: 1155 entries, 0 to 971
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   shapeName   1155 non-null   object
 1   shapeISO    1151 non-null   object
 2   shapeID     1155 non-null   object
 3   shapeGroup  1155 non-null   object
 4   shapeType   1155 non-null   object
 5   geometry    1155 non-null   geometry
dtypes: geometry(1), object(5)
memory usage: 63.2+ KB

In [9]:
db1=db[db['shapeGroup']=='SDN']
#db1.shapeName.tolist()
db2=db1.sort_values('shapeName')
db3=db2[['shapeName','shapeType','shapeID']]
pd.set_option('display.max_columns', 4)
pd.set_option('display.max_rows', 200)
print(db3)

                shapeName shapeType              shapeID
522             Abu Hamed      ADM2    SDN-ADM2-3_0_0-B8
544            Abu Houjar      ADM2   SDN-ADM2-3_0_0-B30
654             Abu Jabra      ADM2  SDN-ADM2-3_0_0-B140
576           Abu Jubaiha      ADM2   SDN-ADM2-3_0_0-B62
624           Abu Karinka      ADM2  SDN-ADM2-3_0_0-B110
650             Abu Zabad      ADM2  SDN-ADM2-3_0_0-B136
640        Abyei - Muglad      ADM2  SDN-ADM2-3_0_0-B126
584        Abyei PCA Area      ADM2   SDN-ADM2-3_0_0-B70
655                 Adila      ADM2  SDN-ADM2-3_0_0-B141
567                  Agig      ADM2   SDN-ADM2-3_0_0-B53
635               Ailliet      ADM2  SDN-ADM2-3_0_0-B121
583              Al Buram      ADM2   SDN-ADM2-3_0_0-B69
531               Al Daba      ADM2   SDN-ADM2-3_0_0-B17
680             Al Mafaza      ADM2  SDN-ADM2-3_0_0-B166
644                Al Qoz      ADM2  SDN-ADM2-3_0_0-B130
643              Al Sunut      ADM2  SDN-ADM2-3_0_0-B129
588            Al Tadamon      ADM2   SDN-ADM2-3_0_0-B74
528              Alborgag      ADM2   SDN-ADM2-3_0_0-B14
530               Algolid      ADM2   SDN-ADM2-3_0_0-B16
620               Alwehda      ADM2  SDN-ADM2-3_0_0-B106
675                 Aroma      ADM2  SDN-ADM2-3_0_0-B161
629              Assalaya      ADM2  SDN-ADM2-3_0_0-B115
526                Atbara      ADM2   SDN-ADM2-3_0_0-B12
676          Atbara River      ADM2  SDN-ADM2-3_0_0-B162
589                  Azum      ADM2   SDN-ADM2-3_0_0-B75
641              Babanusa      ADM2  SDN-ADM2-3_0_0-B127
627          Bahr El Arab      ADM2  SDN-ADM2-3_0_0-B113
534                  Bara      ADM2   SDN-ADM2-3_0_0-B20
527                Barbar      ADM2   SDN-ADM2-3_0_0-B13
570               Basonda      ADM2   SDN-ADM2-3_0_0-B56
587                   Bau      ADM2   SDN-ADM2-3_0_0-B73
590                 Beida      ADM2   SDN-ADM2-3_0_0-B76
628                Bielel      ADM2  SDN-ADM2-3_0_0-B114
591               Bindisi      ADM2   SDN-ADM2-3_0_0-B77
135       Blue Nile State      ADM1   SDN-ADM1-3_0_0-B16
659                 Buram      ADM2  SDN-ADM2-3_0_0-B145
129        Central Darfur      ADM1   SDN-ADM1-3_0_0-B10
663                 Dalgo      ADM2  SDN-ADM2-3_0_0-B149
592          Dar El Salam      ADM2   SDN-ADM2-3_0_0-B78
579               Dilling      ADM2   SDN-ADM2-3_0_0-B65
638                 Dimsu      ADM2  SDN-ADM2-3_0_0-B124
529               Dongola      ADM2   SDN-ADM2-3_0_0-B15
674                Dordeb      ADM2  SDN-ADM2-3_0_0-B160
128     East Darfur State      ADM1    SDN-ADM1-3_0_0-B9
574    Eastern El Galabat      ADM2   SDN-ADM2-3_0_0-B60
540     Eastern El Gezira      ADM2   SDN-ADM2-3_0_0-B26
548        Eastern Sennar      ADM2   SDN-ADM2-3_0_0-B34
616              Ed Daein      ADM2  SDN-ADM2-3_0_0-B102
525              Ed Damer      ADM2   SDN-ADM2-3_0_0-B11
617          Ed El Fursan      ADM2  SDN-ADM2-3_0_0-B103
646           El Abassiya      ADM2  SDN-ADM2-3_0_0-B132
678             El Butana      ADM2  SDN-ADM2-3_0_0-B164
546               El Dali      ADM2   SDN-ADM2-3_0_0-B32
671           El Damazine      ADM2  SDN-ADM2-3_0_0-B157
652             El Dindir      ADM2  SDN-ADM2-3_0_0-B138
550             El Douiem      ADM2   SDN-ADM2-3_0_0-B36
568            El Fashaga      ADM2   SDN-ADM2-3_0_0-B54
593             El Fasher      ADM2   SDN-ADM2-3_0_0-B79
679                El Faw      ADM2  SDN-ADM2-3_0_0-B165
657            El Ferdous      ADM2  SDN-ADM2-3_0_0-B143
594            El Geneina      ADM2   SDN-ADM2-3_0_0-B80
555            El Gutaina      ADM2   SDN-ADM2-3_0_0-B41
541          El Hasaheesa      ADM2   SDN-ADM2-3_0_0-B27
556           El Jabalian      ADM2   SDN-ADM2-3_0_0-B42
542            El Kamleen      ADM2   SDN-ADM2-3_0_0-B28
595               El Kuma      ADM2   SDN-ADM2-3_0_0-B81
665             El Kurmuk      ADM2  SDN-ADM2-3_0_0-B151
596              El Malha      ADM2   SDN-ADM2-3_0_0-B82
543           El Manageel      ADM2   SDN-ADM2-3_0_0-B29
523           El Matammah      ADM2    SDN-ADM2-3_0_0-B9
651             El Nehoud      ADM2  SDN-ADM2-3_0_0-B137
565              El Qaneb      ADM2   SDN-ADM2-3_0_0-B51
569            El Quresha      ADM2   SDN-ADM2-3_0_0-B55
656             El Radoom      ADM2  SDN-ADM2-3_0_0-B142
681              El Rahad      ADM2  SDN-ADM2-3_0_0-B167
653           El Roseires      ADM2  SDN-ADM2-3_0_0-B139
642              El Salam      ADM2  SDN-ADM2-3_0_0-B128
632              El Salam      ADM2  SDN-ADM2-3_0_0-B118
647              El Salam      ADM2  SDN-ADM2-3_0_0-B133
597             El Sireaf      ADM2   SDN-ADM2-3_0_0-B83
547              El Souki      ADM2   SDN-ADM2-3_0_0-B33
598           El Taweisha      ADM2   SDN-ADM2-3_0_0-B84
637               El Tina      ADM2  SDN-ADM2-3_0_0-B123
599          Foro Baranga      ADM2   SDN-ADM2-3_0_0-B85
572               Gedaref      ADM2   SDN-ADM2-3_0_0-B58
133         Gedarif State      ADM1   SDN-ADM1-3_0_0-B14
666               Geissan      ADM2  SDN-ADM2-3_0_0-B152
622               Gereida      ADM2  SDN-ADM2-3_0_0-B108
132          Gezira State      ADM1   SDN-ADM1-3_0_0-B13
639              Ghubaysh      ADM2  SDN-ADM2-3_0_0-B125
537    Greater Wad Madani      ADM2   SDN-ADM2-3_0_0-B23
586                Habila      ADM2   SDN-ADM2-3_0_0-B72
600                Habila      ADM2   SDN-ADM2-3_0_0-B86
562               Halayeb      ADM2   SDN-ADM2-3_0_0-B48
664                 Halfa      ADM2  SDN-ADM2-3_0_0-B150
557      Halfa El Jadeeda      ADM2   SDN-ADM2-3_0_0-B43
559          Hamashkoreib      ADM2   SDN-ADM2-3_0_0-B45
566                  Haya      ADM2   SDN-ADM2-3_0_0-B52
580                Heiban      ADM2   SDN-ADM2-3_0_0-B66
515           Jabal Aulia      ADM2    SDN-ADM2-3_0_0-B1
563      Jabiet Al Maadin      ADM2   SDN-ADM2-3_0_0-B49
601            Jebel Moon      ADM2   SDN-ADM2-3_0_0-B87
535      Jebrat El Sheikh      ADM2   SDN-ADM2-3_0_0-B21
582               Kadugli      ADM2   SDN-ADM2-3_0_0-B68
604             Kalimendo      ADM2   SDN-ADM2-3_0_0-B90
519                Karari      ADM2    SDN-ADM2-3_0_0-B5
618                  Kass      ADM2  SDN-ADM2-3_0_0-B104
683               Kassala      ADM2  SDN-ADM2-3_0_0-B169
123         Kassala State      ADM1    SDN-ADM1-3_0_0-B4
626               Katayla      ADM2  SDN-ADM2-3_0_0-B112
602             Kebkabiya      ADM2   SDN-ADM2-3_0_0-B88
575                Keilak      ADM2   SDN-ADM2-3_0_0-B61
521              Khartoum      ADM2    SDN-ADM2-3_0_0-B7
517        Khartoum North      ADM2    SDN-ADM2-3_0_0-B3
131        Khartoum State      ADM1   SDN-ADM1-3_0_0-B12
677         Khashm Ghirba      ADM2  SDN-ADM2-3_0_0-B163
634                Kornoi      ADM2  SDN-ADM2-3_0_0-B120
553                 Kosti      ADM2   SDN-ADM2-3_0_0-B39
603               Kreinik      ADM2   SDN-ADM2-3_0_0-B89
625                 Kubum      ADM2  SDN-ADM2-3_0_0-B111
605                Kulbus      ADM2   SDN-ADM2-3_0_0-B91
606                 Kutum      ADM2   SDN-ADM2-3_0_0-B92
585                Lagawa      ADM2   SDN-ADM2-3_0_0-B71
668              Marshang      ADM2  SDN-ADM2-3_0_0-B154
607                Mellit      ADM2   SDN-ADM2-3_0_0-B93
532                Merawi      ADM2   SDN-ADM2-3_0_0-B18
573        Middle Gedaref      ADM2   SDN-ADM2-3_0_0-B59
608                Mukjar      ADM2   SDN-ADM2-3_0_0-B94
609               Nertiti      ADM2   SDN-ADM2-3_0_0-B95
621               Niteaga      ADM2  SDN-ADM2-3_0_0-B107
126    North Darfur State      ADM1    SDN-ADM1-3_0_0-B7
673           North Delta      ADM2  SDN-ADM2-3_0_0-B159
127  North Kordofan State      ADM1    SDN-ADM1-3_0_0-B8
136        Northern State      ADM1   SDN-ADM1-3_0_0-B17
633                 Nyala      ADM2  SDN-ADM2-3_0_0-B119
630           Nyala North      ADM2  SDN-ADM2-3_0_0-B116
560            Port Sudan      ADM2   SDN-ADM2-3_0_0-B46
571         Qala El Nahal      ADM2   SDN-ADM2-3_0_0-B57
552                 Rabak      ADM2   SDN-ADM2-3_0_0-B38
667        Rahad El Berdi      ADM2  SDN-ADM2-3_0_0-B153
645                Rashad      ADM2  SDN-ADM2-3_0_0-B131
130         Red Sea State      ADM1   SDN-ADM1-3_0_0-B11
581          Reif Ashargi      ADM2   SDN-ADM2-3_0_0-B67
124      River Nile State      ADM1    SDN-ADM1-3_0_0-B5
610                Rokoro      ADM2   SDN-ADM2-3_0_0-B96
558         Rural Kassala      ADM2   SDN-ADM2-3_0_0-B44
611            Saraf Omra      ADM2   SDN-ADM2-3_0_0-B97
545                Sennar      ADM2   SDN-ADM2-3_0_0-B31
125          Sennar State      ADM1    SDN-ADM1-3_0_0-B6
619     Sharg Jabel Marra      ADM2  SDN-ADM2-3_0_0-B105
518         Sharq El Nile      ADM2    SDN-ADM2-3_0_0-B4
623               Shattai      ADM2  SDN-ADM2-3_0_0-B109
669               Sheiria      ADM2  SDN-ADM2-3_0_0-B155
524                Shendi      ADM2   SDN-ADM2-3_0_0-B10
649               Shiekan      ADM2  SDN-ADM2-3_0_0-B135
549                 Singa      ADM2   SDN-ADM2-3_0_0-B35
672                Sinkat      ADM2  SDN-ADM2-3_0_0-B158
612                 Sirba      ADM2   SDN-ADM2-3_0_0-B98
533                Sodari      ADM2   SDN-ADM2-3_0_0-B19
120    South Darfur State      ADM1    SDN-ADM1-3_0_0-B1
121  South Kordofan State      ADM1    SDN-ADM1-3_0_0-B2
538    Southern El Gezira      ADM2   SDN-ADM2-3_0_0-B24
564                Suakin      ADM2   SDN-ADM2-3_0_0-B50
8                   Sudan      ADM0    SDN-ADM0-3_0_0-B1
658                 Sunta      ADM2  SDN-ADM2-3_0_0-B144
577                Talodi      ADM2   SDN-ADM2-3_0_0-B63
636               Tawilla      ADM2  SDN-ADM2-3_0_0-B122
686                Telkok      ADM2  SDN-ADM2-3_0_0-B172
554              Tendalti      ADM2   SDN-ADM2-3_0_0-B40
561                 Tokar      ADM2   SDN-ADM2-3_0_0-B47
670                Tullus      ADM2  SDN-ADM2-3_0_0-B156
662               Um Buru      ADM2  SDN-ADM2-3_0_0-B148
660              Um Dafug      ADM2  SDN-ADM2-3_0_0-B146
520             Um Durman      ADM2    SDN-ADM2-3_0_0-B6
539            Um El Qura      ADM2   SDN-ADM2-3_0_0-B25
648             Um Rawaba      ADM2  SDN-ADM2-3_0_0-B134
516             Umm Badda      ADM2    SDN-ADM2-3_0_0-B2
661            Umm Dukhun      ADM2  SDN-ADM2-3_0_0-B147
578            Umm Durein      ADM2   SDN-ADM2-3_0_0-B64
613           Umm Keddada      ADM2   SDN-ADM2-3_0_0-B99
551            Umm Ramtta      ADM2   SDN-ADM2-3_0_0-B37
536             Wad Banda      ADM2   SDN-ADM2-3_0_0-B22
684          Wad El Helew      ADM2  SDN-ADM2-3_0_0-B170
614            Wadi Salih      ADM2  SDN-ADM2-3_0_0-B100
122     West Darfur State      ADM1    SDN-ADM1-3_0_0-B3
137         West Kurdufan      ADM1   SDN-ADM1-3_0_0-B18
682    Western El Galabat      ADM2  SDN-ADM2-3_0_0-B168
685       Western Kassala      ADM2  SDN-ADM2-3_0_0-B171
134      White Nile State      ADM1   SDN-ADM1-3_0_0-B15
631                Yassin      ADM2  SDN-ADM2-3_0_0-B117
615              Zalingei      ADM2  SDN-ADM2-3_0_0-B101

In [10]:
dfb_fl_ea['location_count']=dfb_fl_ea.Location.str.count(',')
dfb_fl_ea['adm_lvl_count']=dfb_fl_ea['Adm Level'].str.count(';')
dfb_fl_ea['adm1_count']=dfb_fl_ea['Admin1 Code'].str.count(';')
dfb_fl_ea['adm2_count']=dfb_fl_ea['Admin2 Code'].str.count(';')

<ipython-input-10-a5bee0b1d5a3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['location_count']=dfb_fl_ea.Location.str.count(',')
<ipython-input-10-a5bee0b1d5a3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['adm_lvl_count']=dfb_fl_ea['Adm Level'].str.count(';')
<ipython-input-10-a5bee0b1d5a3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['adm1_count']=dfb_fl_ea['Admin1 Code'].str.count(';')
<ipython-input-10-a5bee0b1d5a3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['adm2_count']=dfb_fl_ea['Admin2 Code'].str.count(';')

## replacing GAUL Admin1 Code into GEOB admin2 codes

In [11]:
dfb_fl_ea['gaul_adm1_list']=dfb_fl_ea['Admin1 Code'].str.split(';')


em_dat_path='data/'


gaul_adm1_dict_db=pd.read_csv(f'{em_dat_path}em_dat_ea_gaul_geob_adm1_codeshare.csv')

gaul_adm1_dict = dict(zip(gaul_adm1_dict_db.gaul_adm1_code, gaul_adm1_dict_db.geob_adm1_shapeID))


dfb_fl_ea_adm1=dfb_fl_ea[dfb_fl_ea['gaul_adm1_list'].notna()]

dfb_fl_ea_adm1['gaul_adm1_list_int']=dfb_fl_ea_adm1['gaul_adm1_list'].apply(lambda x: [int(i) for i in x])


dfb_fl_ea_adm1['gaul_adm1_geob'] = dfb_fl_ea_adm1['gaul_adm1_list_int'].apply(lambda x: [gaul_adm1_dict[i] for i in x])

#dfb_dr_adm1

dfb_fl_ea_adm1_a=dfb_fl_ea_adm1[['Dis No','gaul_adm1_geob']]

dfb_fl_ea_adm1_a.info()

<ipython-input-11-455a25f38b2c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['gaul_adm1_list']=dfb_fl_ea['Admin1 Code'].str.split(';')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 1033 to 4571
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dis No          99 non-null     object
 1   gaul_adm1_geob  99 non-null     object
dtypes: object(2)
memory usage: 2.3+ KB

<ipython-input-11-455a25f38b2c>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_adm1['gaul_adm1_list_int']=dfb_fl_ea_adm1['gaul_adm1_list'].apply(lambda x: [int(i) for i in x])
<ipython-input-11-455a25f38b2c>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_adm1['gaul_adm1_geob'] = dfb_fl_ea_adm1['gaul_adm1_list_int'].apply(lambda x: [gaul_adm1_dict[i] for i in x])

 ## replace adm1 code with adm2 sub codes

In [20]:
import geopandas as gp
import numpy as np

geob_adm1_adm2_filepath='data/'


geob_db=gp.read_file(f'{geob_adm1_adm2_filepath}ea_adm2_geoboundaries_adm1_code.shp')


#https://stackoverflow.com/a/54137935/2501953


geob_db1=geob_db[['adm1_shape','shapeID']]
#geob_db2=geob_db1.set_index('adm1_shape')


#geob_db_dict=geob_db1['adm1_shape'].groupby(level=0).apply(lambda x: x.to_dict('shapeID')).to_dict()

geob_db2=geob_db1.groupby('adm1_shape').agg({'shapeID':lambda x: list(x)})
geob_db3=geob_db2.reset_index()
geob_db3.columns=['gaul_adm1_geob','shapeID']

geob_db3_dict = dict(zip(geob_db3.gaul_adm1_geob, geob_db3.shapeID))


dfb_fl_ea_adm1_a['geob_adm2'] = dfb_fl_ea_adm1_a['gaul_adm1_geob'].apply(lambda x: [geob_db3_dict[i] for i in x])

def flatten(l):
    return [item for sublist in l for item in sublist]

aa_list=[]
for idx,row in dfb_fl_ea_adm1_a.iterrows():
    aa=flatten(row['geob_adm2'])
    #print(aa)
    #dfb_dr_adm1_a.at[idx,'geob_adm2_list'] = list(flatten(row['geob_adm2']))
    aa_list.append(aa)
    aa=[]
    
dfb_fl_ea_adm1_a['geob_adm2_list']=aa_list
    
dfb_fl_part1=dfb_fl_ea_adm1_a[['Dis No','geob_adm2_list']]
dfb_fl_part1

<ipython-input-20-ba72e794a77a>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_adm1_a['geob_adm2'] = dfb_fl_ea_adm1_a['gaul_adm1_geob'].apply(lambda x: [geob_db3_dict[i] for i in x])
<ipython-input-20-ba72e794a77a>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea_adm1_a['geob_adm2_list']=aa_list

             Dis No                                     geob_adm2_list
1033  2000-0259-SOM  [SOM-ADM2-3_0_0-B18, SOM-ADM2-3_0_0-B38, SOM-A...
1034  2000-0778-SOM  [SOM-ADM2-3_0_0-B17, SOM-ADM2-3_0_0-B40, SOM-A...
1046  2000-0790-TZA  [TZA-ADM2-3_0_0-B22, TZA-ADM2-3_0_0-B32, TZA-A...
1169  2001-0464-ETH  [ETH-ADM2-3_0_0-B2, ETH-ADM2-3_0_0-B38, ETH-AD...
1252  2002-0225-ETH  [ETH-ADM2-3_0_0-B70, ETH-ADM2-3_0_0-B71, ETH-A...
1371  2001-0672-RWA  [RWA-ADM2-3_0_0-B18, RWA-ADM2-3_0_0-B19, RWA-A...
1372  2001-0417-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
1442  2002-0273-RWA  [RWA-ADM2-3_0_0-B1, RWA-ADM2-3_0_0-B2, RWA-ADM...
1503  2002-0515-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
1509  2002-0715-SOM  [SOM-ADM2-3_0_0-B21, SOM-ADM2-3_0_0-B25, SOM-A...
1645  2003-0204-ETH  [ETH-ADM2-3_0_0-B1, ETH-ADM2-3_0_0-B14, ETH-AD...
1730  2003-0368-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
1786  2003-0204-SOM  [SOM-ADM2-3_0_0-B17, SOM-ADM2-3_0_0-B40, SOM-A...
1902  2004-0499-SOM  [SOM-ADM2-3_0_0-B3, SOM-ADM2-3_0_0-B28, SOM-AD...
1976  2005-0215-ETH  [ETH-ADM2-3_0_0-B13, ETH-ADM2-3_0_0-B1, ETH-AD...
1979  2005-0485-ETH  [ETH-ADM2-3_0_0-B6, ETH-ADM2-3_0_0-B15, ETH-AD...
2008  2005-0258-ETH                               [ETH-ADM2-3_0_0-B13]
2009  2005-0472-ETH  [ETH-ADM2-3_0_0-B4, ETH-ADM2-3_0_0-B7, ETH-ADM...
2078  2006-0204-ETH  [ETH-ADM2-3_0_0-B70, ETH-ADM2-3_0_0-B71, ETH-A...
2079  2006-0436-ETH  [ETH-ADM2-3_0_0-B11, ETH-ADM2-3_0_0-B19, ETH-A...
2081  2006-0442-ETH  [ETH-ADM2-3_0_0-B70, ETH-ADM2-3_0_0-B71, ETH-A...
2082  2006-0489-ETH  [ETH-ADM2-3_0_0-B2, ETH-ADM2-3_0_0-B38, ETH-AD...
2111  2005-0576-SDN  [SDN-ADM2-3_0_0-B46, SDN-ADM2-3_0_0-B47, SDN-A...
2115  2005-0215-KEN  [KEN-ADM2-3_0_0-B12, KEN-ADM2-3_0_0-B53, KEN-A...
2116  2005-0260-KEN  [KEN-ADM2-3_0_0-B1, KEN-ADM2-3_0_0-B23, KEN-AD...
2212  2006-0234-KEN  [KEN-ADM2-3_0_0-B58, KEN-ADM2-3_0_0-B12, KEN-A...
2296  2006-0229-SOM  [SOM-ADM2-3_0_0-B18, SOM-ADM2-3_0_0-B38, SOM-A...
2300  2006-0624-SOM  [SOM-ADM2-3_0_0-B21, SOM-ADM2-3_0_0-B25, SOM-A...
2313  2006-0624-TZA  [TZA-ADM2-3_0_0-B12, TZA-ADM2-3_0_0-B35, TZA-A...
2451  2007-0304-ETH  [ETH-ADM2-3_0_0-B48, ETH-ADM2-3_0_0-B70, ETH-A...
2514  2008-0386-ETH  [ETH-ADM2-3_0_0-B2, ETH-ADM2-3_0_0-B38, ETH-AD...
2611  2007-0261-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
2735  2008-0066-TZA  [TZA-ADM2-3_0_0-B9, TZA-ADM2-3_0_0-B27, TZA-AD...
2828  2008-0331-SSD  [SSD-ADM2-3_0_0-B37, SSD-ADM2-3_0_0-B38, SSD-A...
2829  2008-0520-SSD  [SSD-ADM2-3_0_0-B28, SSD-ADM2-3_0_0-B29, SSD-A...
2830  2008-0554-SSD  [SSD-ADM2-3_0_0-B15, SSD-ADM2-3_0_0-B16, SSD-A...
2909  2010-0450-ETH  [ETH-ADM2-3_0_0-B70, ETH-ADM2-3_0_0-B71, ETH-A...
2943  2009-0494-KEN  [KEN-ADM2-3_0_0-B12, KEN-ADM2-3_0_0-B53, KEN-A...
2946  2009-0484-TZA  [TZA-ADM2-3_0_0-B12, TZA-ADM2-3_0_0-B35, TZA-A...
2981  2009-0379-SDN  [SDN-ADM2-3_0_0-B73, SDN-ADM2-3_0_0-B74, SDN-A...
2990  2009-0591-TZA  [TZA-ADM2-3_0_0-B14, TZA-ADM2-3_0_0-B34, TZA-A...
3006  2010-0285-KEN            [KEN-ADM2-3_0_0-B4, KEN-ADM2-3_0_0-B43]
3045  2010-0319-SDN  [SDN-ADM2-3_0_0-B46, SDN-ADM2-3_0_0-B47, SDN-A...
3046  2010-0579-SDN  [SDN-ADM2-3_0_0-B8, SDN-ADM2-3_0_0-B9, SDN-ADM...
3055  2010-0115-SOM  [SOM-ADM2-3_0_0-B6, SOM-ADM2-3_0_0-B8, SOM-ADM...
3056  2010-0164-SOM  [SOM-ADM2-3_0_0-B35, SOM-ADM2-3_0_0-B58, SOM-A...
3169  2010-0579-SSD  [SSD-ADM2-3_0_0-B15, SSD-ADM2-3_0_0-B16, SSD-A...
3170  2010-0703-SSD  [SSD-ADM2-3_0_0-B28, SSD-ADM2-3_0_0-B29, SSD-A...
3302  2011-0634-TZA  [TZA-ADM2-3_0_0-B18, TZA-ADM2-3_0_0-B37, TZA-A...
3344  2011-0617-TZA  [TZA-ADM2-3_0_0-B86, TZA-ADM2-3_0_0-B97, TZA-A...
3383  2012-0280-SDN  [SDN-ADM2-3_0_0-B1, SDN-ADM2-3_0_0-B2, SDN-ADM...
3395  2012-0472-SOM  [SOM-ADM2-3_0_0-B18, SOM-ADM2-3_0_0-B38, SOM-A...
3411  2013-0123-KEN  [KEN-ADM2-3_0_0-B58, KEN-ADM2-3_0_0-B4, KEN-AD...
3455  2013-0280-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
3467  2013-0288-SOM  [SOM-ADM2-3_0_0-B5, SOM-ADM2-3_0_0-B14, SOM-AD...
3513  2012-0473-SSD  [SSD-ADM2-3_0_0-B15, SSD-ADM2-3_0_0-B16, SSD-A...
3529  2013-0425-SSD  [SSD-ADM2-3_0_0-B23, SSD-ADM2-3_0_0-B24, SSD-A...
3530  2013-0453-SSD  [SSD-ADM2-3_0_0-B23, SSD-ADM2-3_0_0-B24, SSD-A...
3611  2016-0101-ETH  [ETH-ADM2-3_0_0-B70, ETH-ADM2-3_0_0-B71, ETH-A...
3675  2014-0264-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
3682  2014-0456-SOM  [SOM-ADM2-3_0_0-B5, SOM-ADM2-3_0_0-B14, SOM-AD...
3721  2015-0392-SDN  [SDN-ADM2-3_0_0-B8, SDN-ADM2-3_0_0-B9, SDN-ADM...
3726  2015-0477-SOM  [SOM-ADM2-3_0_0-B27, SOM-ADM2-3_0_0-B29, SOM-A...
3727  2015-0544-SOM  [SOM-ADM2-3_0_0-B5, SOM-ADM2-3_0_0-B14, SOM-AD...
3746  2016-0129-SOM  [SOM-ADM2-3_0_0-B35, SOM-ADM2-3_0_0-B58, SOM-A...
3755  2014-0119-TZA  [TZA-ADM2-3_0_0-B11, TZA-ADM2-3_0_0-B25, TZA-A...
3790  2015-0205-TZA  [TZA-ADM2-3_0_0-B14, TZA-ADM2-3_0_0-B34, TZA-A...
3820  2016-0028-TZA  [TZA-ADM2-3_0_0-B12, TZA-ADM2-3_0_0-B35, TZA-A...
3940  2017-0205-KEN  [KEN-ADM2-3_0_0-B52, KEN-ADM2-3_0_0-B58, KEN-A...
3994  2018-0116-KEN                               [KEN-ADM2-3_0_0-B46]
4052  2016-0274-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
4072  2016-0327-SSD  [SSD-ADM2-3_0_0-B28, SSD-ADM2-3_0_0-B29, SSD-A...
4084  2017-0573-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
4094  2017-0205-TZA  [TZA-ADM2-3_0_0-B13, TZA-ADM2-3_0_0-B30, TZA-A...
4124  2018-0387-SDN  [SDN-ADM2-3_0_0-B1, SDN-ADM2-3_0_0-B2, SDN-ADM...
4127  2018-0292-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
4129  2018-0133-SOM  [SOM-ADM2-3_0_0-B10, SOM-ADM2-3_0_0-B13, SOM-A...
4140  2018-0125-TZA  [TZA-ADM2-3_0_0-B14, TZA-ADM2-3_0_0-B34, TZA-A...
4167  2019-0579-DJI  [DJI-ADM2-3_0_0-B10, DJI-ADM2-3_0_0-B7, DJI-AD...
4259  2019-0500-ETH  [ETH-ADM2-3_0_0-B1, ETH-ADM2-3_0_0-B14, ETH-AD...
4308  2020-0159-ETH  [ETH-ADM2-3_0_0-B13, ETH-ADM2-3_0_0-B3, ETH-AD...
4423  2019-0654-RWA  [RWA-ADM2-3_0_0-B1, RWA-ADM2-3_0_0-B2, RWA-ADM...
4424  2019-0392-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
4427  2019-0280-SDN  [SDN-ADM2-3_0_0-B78, SDN-ADM2-3_0_0-B79, SDN-A...
4431  2019-0500-SOM  [SOM-ADM2-3_0_0-B10, SOM-ADM2-3_0_0-B13, SOM-A...
4436  2019-0562-TZA  [TZA-ADM2-3_0_0-B22, TZA-ADM2-3_0_0-B32, TZA-A...
4439  2019-0496-TZA  [TZA-ADM2-3_0_0-B86, TZA-ADM2-3_0_0-B97, TZA-A...
4464  2019-0285-SSD  [SSD-ADM2-3_0_0-B1, SSD-ADM2-3_0_0-B2, SSD-ADM...
4471  2020-0041-RWA  [RWA-ADM2-3_0_0-B1, RWA-ADM2-3_0_0-B2, RWA-ADM...
4473  2020-0166-TZA  [TZA-ADM2-3_0_0-B14, TZA-ADM2-3_0_0-B34, TZA-A...
4480  2020-0305-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
4487  2020-0320-SOM  [SOM-ADM2-3_0_0-B10, SOM-ADM2-3_0_0-B13, SOM-A...
4488  2020-0159-SOM  [SOM-ADM2-3_0_0-B35, SOM-ADM2-3_0_0-B58, SOM-A...
4496  2020-0037-TZA  [TZA-ADM2-3_0_0-B10, TZA-ADM2-3_0_0-B31, TZA-A...
4497  2020-0458-TZA  [TZA-ADM2-3_0_0-B11, TZA-ADM2-3_0_0-B25, TZA-A...
4522  2020-0362-SSD  [SSD-ADM2-3_0_0-B15, SSD-ADM2-3_0_0-B16, SSD-A...
4541  2021-0473-SDN  [SDN-ADM2-3_0_0-B23, SDN-ADM2-3_0_0-B24, SDN-A...
4544  2021-0239-SOM  [SOM-ADM2-3_0_0-B35, SOM-ADM2-3_0_0-B58, SOM-A...
4571  2021-0481-SSD  [SSD-ADM2-3_0_0-B28, SSD-ADM2-3_0_0-B29, SSD-A...

## replacing GAUL Admin2 Code into GEOB admin2 codes

In [21]:
dfb_fl_ea['gaul_adm2_list']=dfb_fl_ea['Admin2 Code'].str.split(';')


em_dat_path='data/'


gaul_adm2_dict_db=pd.read_excel(f'{em_dat_path}em_dat_ea_gaul_geob_adm2_codeshare_v1.xlsx', engine='openpyxl')

gaul_adm2_dict = dict(zip(gaul_adm2_dict_db.gaul_adm2_code, gaul_adm2_dict_db.geob_adm2_shapeID))

gaul_adm2_dict[48481]='TZA-ADM1-3_0_0-B2'
gaul_adm2_dict[48451]='TZA-ADM1-3_0_0-B8'

#48481:TZA-ADM1-3_0_0-B2
#48451:TZA-ADM1-3_0_0-B8

dfb_fl_adm2=dfb_fl_ea[dfb_fl_ea['gaul_adm2_list'].notna()]

dfb_fl_adm2['gaul_adm2_list_int']=dfb_fl_adm2['gaul_adm2_list'].apply(lambda x: [int(i) for i in x])

#dfb_fl_adm2a=dfb_fl_adm2[dfb_fl_adm2['gaul_adm2_list_int']==48481]


dfb_fl_adm2['gaul_adm2_geob'] = dfb_fl_adm2['gaul_adm2_list_int'].apply(lambda x: [gaul_adm2_dict[i] for i in x])

# _b_dict={1:'TZA-ADM1-3_0_0-B2',2:'TZA-ADM1-3_0_0-B8'}

# dfb_fl_adm2['gaul_adm2_geob'] = dfb_fl_adm2['gaul_adm2_geob'].apply(lambda x: [_b_dict[i] for i in x])
# #dfb_dr_a

dfb_fl_part2=dfb_fl_adm2[['Dis No','gaul_adm2_geob']]

dfb_fl_part2.columns=['Dis No','geob_adm2_list']




dfb_fl_part2

<ipython-input-21-9063970f4954>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_ea['gaul_adm2_list']=dfb_fl_ea['Admin2 Code'].str.split(';')
<ipython-input-21-9063970f4954>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_adm2['gaul_adm2_list_int']=dfb_fl_adm2['gaul_adm2_list'].apply(lambda x: [int(i) for i in x])
<ipython-input-21-9063970f4954>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_adm2['gaul_adm2_geob'] = dfb_fl_adm2['gaul_adm2_list_int'].apply(lambda x: [gaul_adm2_dict[i] for i in x])

             Dis No                                     geob_adm2_list
785   2000-0497-ETH                               [ETH-ADM2-3_0_0-B70]
796   2000-0399-ETH           [ETH-ADM2-3_0_0-B48, ETH-ADM2-3_0_0-B17]
910   2001-0032-KEN                               [KEN-ADM2-3_0_0-B46]
1033  2000-0259-SOM  [SOM-ADM2-3_0_0-B17, SOM-ADM2-3_0_0-B33, SOM-A...
1039  2000-0490-SOM                               [SOM-ADM2-3_0_0-B68]
1164  2001-0448-ETH                               [ETH-ADM2-3_0_0-B70]
1170  2001-0769-ETH                               [ETH-ADM2-3_0_0-B67]
1214  2002-0265-KEN  [KEN-ADM2-3_0_0-B20, KEN-ADM2-3_0_0-B44, KEN-A...
1270  2002-0711-KEN                               [KEN-ADM2-3_0_0-B18]
1271  2002-0689-KEN           [KEN-ADM2-3_0_0-B25, KEN-ADM2-3_0_0-B58]
1272  2002-0800-KEN                                [KEN-ADM2-3_0_0-B1]
1370  2001-0541-RWA                                [RWA-ADM2-3_0_0-B6]
1380  2001-0653-SOM                               [SOM-ADM2-3_0_0-B16]
1391  2001-0109-TZA  [TZA-ADM2-3_0_0-B25, TZA-ADM2-3_0_0-B11, TZA-A...
1442  2002-0273-RWA  [RWA-ADM2-3_0_0-B22, RWA-ADM2-3_0_0-B12, RWA-A...
1503  2002-0515-SDN  [SDN-ADM2-3_0_0-B126, SDN-ADM2-3_0_0-B128, SDN...
1509  2002-0715-SOM           [SOM-ADM2-3_0_0-B40, SOM-ADM2-3_0_0-B33]
1519  2002-0274-TZA            [TZA-ADM2-3_0_0-B50, TZA-ADM2-3_0_0-B4]
1613  2003-0204-KEN  [KEN-ADM2-3_0_0-B21, KEN-ADM2-3_0_0-B40, KEN-A...
1644  2003-0368-ERI                                [ERI-ADM2-3_0_0-B1]
1651  2003-0729-KEN                               [KEN-ADM2-3_0_0-B21]
1656  2004-0158-DJI                                [DJI-ADM2-3_0_0-B8]
1658  2004-0194-KEN  [KEN-ADM2-3_0_0-B57, KEN-ADM2-3_0_0-B58, KEN-A...
1661  2004-0394-ERI                               [ERI-ADM2-3_0_0-B14]
1710  2004-0152-KEN            [KEN-ADM2-3_0_0-B51, KEN-ADM2-3_0_0-B6]
1771  2003-0563-RWA           [RWA-ADM2-3_0_0-B22, RWA-ADM2-3_0_0-B24]
1787  2003-0447-SOM           [SOM-ADM2-3_0_0-B23, SOM-ADM2-3_0_0-B46]
1792  2003-0620-TZA                               [TZA-ADM2-3_0_0-B63]
2077  2006-0422-ETH           [ETH-ADM2-3_0_0-B13, ETH-ADM2-3_0_0-B48]
2080  2006-0438-ETH                               [ETH-ADM2-3_0_0-B56]
2083  2006-0578-ETH           [ETH-ADM2-3_0_0-B51, ETH-ADM2-3_0_0-B35]
2115  2005-0215-KEN           [KEN-ADM2-3_0_0-B13, KEN-ADM2-3_0_0-B69]
2116  2005-0260-KEN                               [KEN-ADM2-3_0_0-B69]
2117  2005-0526-KEN                                [KEN-ADM2-3_0_0-B6]
2165  2005-0748-SDN             [SDN-ADM2-3_0_0-B3, SDN-ADM2-3_0_0-B2]
2174  2005-0215-SOM  [SOM-ADM2-3_0_0-B35, SOM-ADM2-3_0_0-B38, SOM-A...
2175  2005-0309-SOM                               [SOM-ADM2-3_0_0-B33]
2186  2005-0212-TZA         [TZA-ADM2-3_0_0-B168, TZA-ADM2-3_0_0-B163]
2207  2006-0447-SDN                               [SDN-ADM2-3_0_0-B18]
2211  2006-0178-KEN  [KEN-ADM2-3_0_0-B13, KEN-ADM2-3_0_0-B42, KEN-A...
2213  2006-0587-KEN  [KEN-ADM2-3_0_0-B25, KEN-ADM1-3_0_0-B34, KEN-A...
2214  2006-0624-KEN  [KEN-ADM2-3_0_0-B19, KEN-ADM2-3_0_0-B25, KEN-A...
2284  2006-0422-SDN                               [SDN-ADM2-3_0_0-B30]
2285  2006-0442-SDN  [SDN-ADM2-3_0_0-B60, SDN-ADM2-3_0_0-B166, SDN-...
2297  2006-0422-SOM                               [SOM-ADM2-3_0_0-B72]
2298  2006-0550-SOM           [SOM-ADM2-3_0_0-B68, SOM-ADM2-3_0_0-B72]
2299  2006-0618-SOM  [SOM-ADM2-3_0_0-B38, SOM-ADM2-3_0_0-B18, SOM-A...
2312  2006-0255-TZA                               [TZA-ADM2-3_0_0-B78]
2362  2007-0059-RWA           [RWA-ADM2-3_0_0-B15, RWA-ADM2-3_0_0-B14]
2450  2007-0273-ETH                               [ETH-ADM2-3_0_0-B56]
2515  2008-0219-ETH                               [ETH-ADM2-3_0_0-B20]
2516  2008-0517-ETH  [ETH-ADM2-3_0_0-B25, ETH-ADM2-3_0_0-B1, ETH-AD...
2555  2007-0613-KEN                               [KEN-ADM2-3_0_0-B57]
2557  2007-0442-RWA           [RWA-ADM2-3_0_0-B15, RWA-ADM2-3_0_0-B14]
2559  2007-0408-KEN                                [KEN-ADM2-3_0_0-B6]
2560  2007-0425-SOM                               [SOM-ADM2-3_0_0-B72]
2567  2007-0177-KEN  [KEN-ADM2-3_0_0-B19, KEN-ADM2-3_0_0-B25, KEN-A...
2622  2007-0559-SOM                               [SOM-ADM2-3_0_0-B31]
2648  2008-0518-KEN  [KEN-ADM2-3_0_0-B58, KEN-ADM2-3_0_0-B69, KEN-A...
2649  2008-0485-RWA  [RWA-ADM2-3_0_0-B27, RWA-ADM2-3_0_0-B28, RWA-A...
2657  2008-0482-KEN                               [KEN-ADM2-3_0_0-B32]
2658  2008-0127-KEN                               [KEN-ADM2-3_0_0-B57]
2659  2008-0260-KEN                               [KEN-ADM2-3_0_0-B58]
2660  2008-0483-KEN                               [KEN-ADM2-3_0_0-B64]
2665  2008-0129-KEN           [KEN-ADM2-3_0_0-B35, KEN-ADM2-3_0_0-B53]
2721  2008-0506-SOM                               [SOM-ADM2-3_0_0-B42]
2730  2008-0127-TZA                              [TZA-ADM2-3_0_0-B157]
2828  2008-0331-SSD  [SSD-ADM2-3_0_0-B56, SSD-ADM2-3_0_0-B58, SSD-A...
2829  2008-0520-SSD  [SSD-ADM2-3_0_0-B78, SSD-ADM2-3_0_0-B70, SSD-A...
2908  2010-0115-ETH                               [ETH-ADM2-3_0_0-B51]
2943  2009-0494-KEN  [KEN-ADM2-3_0_0-B31, KEN-ADM2-3_0_0-B58, KEN-A...
2944  2009-0597-KEN  [KEN-ADM2-3_0_0-B18, KEN-ADM2-3_0_0-B19, KEN-A...
2985  2009-0532-SOM  [SOM-ADM2-3_0_0-B37, SOM-ADM2-3_0_0-B49, SOM-A...
2990  2009-0591-TZA  [TZA-ADM2-3_0_0-B49, TZA-ADM2-3_0_0-B35, TZA-A...
2998  2010-0094-KEN  [KEN-ADM2-3_0_0-B33, KEN-ADM2-3_0_0-B31, KEN-A...
3006  2010-0285-KEN                                [KEN-ADM2-3_0_0-B1]
3074  2011-0183-RWA  [RWA-ADM2-3_0_0-B5, RWA-ADM2-3_0_0-B20, RWA-AD...
3216  2011-0631-ETH                               [ETH-ADM2-3_0_0-B51]
3292  2013-0125-ETH  [ETH-ADM2-3_0_0-B53, ETH-ADM2-3_0_0-B29, ETH-A...
3314  2011-0423-KEN           [KEN-ADM2-3_0_0-B21, KEN-ADM2-3_0_0-B64]
3315  2011-0476-KEN                               [KEN-ADM2-3_0_0-B69]
3316  2011-0504-KEN  [KEN-ADM2-3_0_0-B44, KEN-ADM2-3_0_0-B58, KEN-A...
3341  2011-0476-SOM                               [SOM-ADM2-3_0_0-B68]
3343  2011-0535-TZA           [TZA-ADM2-3_0_0-B25, TZA-ADM2-3_0_0-B11]
3358  2012-0166-KEN  [KEN-ADM2-3_0_0-B61, KEN-ADM2-3_0_0-B31, KEN-A...
3382  2012-0130-RWA  [RWA-ADM2-3_0_0-B20, RWA-ADM2-3_0_0-B15, RWA-A...
3396  2012-0508-SOM                               [SOM-ADM2-3_0_0-B38]
3401  2012-0072-TZA                              [TZA-ADM2-3_0_0-B102]
3411  2013-0123-KEN  [KEN-ADM2-3_0_0-B18, KEN-ADM2-3_0_0-B44, KEN-A...
3414  2013-0281-KEN                                [KEN-ADM2-3_0_0-B1]
3415  2013-0305-KEN  [KEN-ADM2-3_0_0-B46, KEN-ADM2-3_0_0-B21, KEN-A...
3416  2013-0545-KEN  [KEN-ADM2-3_0_0-B57, KEN-ADM2-3_0_0-B30, KEN-A...
3468  2013-0473-SOM            [SOM-ADM2-3_0_0-B1, SOM-ADM2-3_0_0-B72]
3514  2012-0476-SSD                               [SSD-ADM2-3_0_0-B56]
3603  2015-0548-ETH                               [ETH-ADM2-3_0_0-B51]
3611  2016-0101-ETH           [ETH-ADM2-3_0_0-B20, ETH-ADM2-3_0_0-B68]
3612  2016-0186-ETH            [ETH-ADM2-3_0_0-B68, ETH-ADM2-3_0_0-B7]
3682  2014-0456-SOM  [SOM-ADM2-3_0_0-B15, SOM-ADM2-3_0_0-B25, SOM-A...
3689  2015-0153-RWA           [RWA-ADM2-3_0_0-B30, RWA-ADM2-3_0_0-B14]
3697  2015-0158-KEN                               [KEN-ADM2-3_0_0-B12]
3698  2015-0159-KEN  [KEN-ADM2-3_0_0-B46, KEN-ADM2-3_0_0-B8, KEN-AD...
3699  2015-0564-KEN  [KEN-ADM2-3_0_0-B20, KEN-ADM2-3_0_0-B58, KEN-A...
3731  2016-0149-RWA  [RWA-ADM2-3_0_0-B19, RWA-ADM2-3_0_0-B10, RWA-A...
3732  2016-0161-KEN  [KEN-ADM2-3_0_0-B35, KEN-ADM2-3_0_0-B46, KEN-A...
3736  2016-0089-KEN                               [KEN-ADM2-3_0_0-B64]
3754  2014-0042-TZA  [TZA-ADM2-3_0_0-B97, TZA-ADM2-3_0_0-B120, TZA-...
3755  2014-0119-TZA                               [TZA-ADM2-3_0_0-B50]
3819  2016-0060-TZA                              [TZA-ADM2-3_0_0-B104]
3820  2016-0028-TZA                              [TZA-ADM2-3_0_0-B104]
3821  2016-0244-TZA          [TZA-ADM2-3_0_0-B86, TZA-ADM2-3_0_0-B148]
3983  2018-0104-RWA                               [RWA-ADM2-3_0_0-B14]
3984  2018-0148-KEN                               [KEN-ADM2-3_0_0-B47]
3995  2018-0132-KEN  [KEN-ADM2-3_0_0-B58, KEN-ADM2-3_0_0-B13, KEN-A...
4120  2018-0135-RWA  [RWA-ADM2-3_0_0-B2, RWA-ADM2-3_0_0-B25, RWA-AD...
4124  2018-0387-SDN  [SDN-ADM2-3_0_0-B126, SDN-ADM2-3_0_0-B128, SDN...
4126  2018-0221-SDN          [SDN-ADM2-3_0_0-B74, SDN-ADM2-3_0_0-B101]
4127  2018-0292-SDN  [SDN-ADM2-3_0_0-B126, SDN-ADM2-3_0_0-B128, SDN...
4176  2019-0203-TZA  [TZA-ADM2-3_0_0-B25, TZA-ADM2-3_0_0-B11, TZA-A...
4220  2020-0150-DJI                                [DJI-ADM2-3_0_0-B8]
4250  2019-0500-KEN  [KEN-ADM2-3_0_0-B67, KEN-ADM2-3_0_0-B34, KEN-A...
4297  2020-0164-KEN  [KEN-ADM2-3_0_0-B20, KEN-ADM2-3_0_0-B19, KEN-A...
4310  2020-0564-ETH                               [ETH-ADM2-3_0_0-B55]
4373  2021-0227-KEN  [KEN-ADM2-3_0_0-B58, KEN-ADM2-3_0_0-B35, KEN-A...
4422  2019-0643-RWA  [RWA-ADM2-3_0_0-B5, RWA-ADM2-3_0_0-B20, RWA-AD...
4440  2019-0515-TZA                              [TZA-ADM2-3_0_0-B112]
4465  2019-0486-SSD                               [SSD-ADM2-3_0_0-B78]
4472  2020-0171-RWA  [RWA-ADM2-3_0_0-B25, RWA-ADM2-3_0_0-B22, RWA-A...
4480  2020-0305-SDN                               [SDN-ADM2-3_0_0-B54]
4481  2020-0098-RWA  [RWA-ADM2-3_0_0-B2, RWA-ADM2-3_0_0-B5, RWA-ADM...
4482  2020-0156-RWA  [RWA-ADM2-3_0_0-B19, RWA-ADM2-3_0_0-B22, RWA-A...
4488  2020-0159-SOM           [SOM-ADM2-3_0_0-B38, SOM-ADM2-3_0_0-B72]
4499  2020-0194-TZA                              [TZA-ADM2-3_0_0-B104]
4522  2020-0362-SSD  [SSD-ADM2-3_0_0-B63, SSD-ADM2-3_0_0-B56, SSD-A...
4524  2021-0282-RWA  [RWA-ADM2-3_0_0-B21, RWA-ADM2-3_0_0-B22, RWA-A...
4553  2021-0010-TZA                                [TZA-ADM1-3_0_0-B8]
4571  2021-0481-SSD           [SSD-ADM2-3_0_0-B63, SSD-ADM2-3_0_0-B66]
4573  2022-0055-RWA  [RWA-ADM2-3_0_0-B5, RWA-ADM2-3_0_0-B7, RWA-ADM...
4577  2022-0232-RWA  [RWA-ADM2-3_0_0-B2, RWA-ADM2-3_0_0-B26, RWA-AD...

In [22]:
import geopandas as gp
import glob

shpfiles=glob.glob(f'{shpfile_path}geoboundary_code_flood/*.shp')

for shpfl in shpfiles:
    db=gp.read_file(shpfl)
    db

In [23]:
db

,shapeName,shapeISO,...,shapeType,geometry
0,Burundi,BDI,...,ADM0,"POLYGON ((30.41190 -2.31239, 30.41202 -2.31260..."
1,Djibouti,DJI,...,ADM0,"MULTIPOLYGON (((43.18436 11.72844, 43.18447 11..."
2,Eritrea,ERI,...,ADM0,"MULTIPOLYGON (((42.93967 12.84493, 42.93967 12..."
3,Ethiopia,ETH,...,ADM0,"POLYGON ((37.94631 14.83520, 37.95126 14.83274..."
4,Kenya,KEN,...,ADM0,"POLYGON ((35.93833 4.61944, 35.94423 4.61914, ..."
...,...,...,...,...,...
967,AGAGO,UG-322,...,ADM2,"POLYGON ((33.55052 3.28146, 33.55067 3.27989, ..."
968,KAGADI,None,...,ADM2,"POLYGON ((31.06062 1.16054, 31.06079 1.16050, ..."
969,KIBAALE,UG-407,...,ADM2,"POLYGON ((31.12178 1.00273, 31.12179 1.00232, ..."
970,GULU,UG-304,...,ADM2,"POLYGON ((32.51042 3.16134, 32.51034 3.16057, ..."
971,RUBANDA,None,...,ADM2,"POLYGON ((29.90118 -1.04230, 29.90144 -1.04256..."

## replacing manually added GEOB admin 1 and admin2 codes into common admin2 codes

In [24]:
import pandas as pd
import geopandas as gp
import numpy as np

dfb_fl = pd.read_excel(f'{em_dat_path}ea_flood_missing_location_v2.xlsx', engine='openpyxl')
dfb_fl1 = dfb_fl[dfb_fl['geob'].isna()].copy()
dfb_fl2 = dfb_fl[dfb_fl['geob'].notna()].copy()
dfb_fl2['geob_list'] = dfb_fl2['geob'].str.split(',')

ken = gp.read_file(f'{shpfile_path}1998-0443-KEN.shp')
ken_list = ken['shapeID'].tolist()
som94 = gp.read_file(f'{shpfile_path}/1994-0573-SOM.shp')
som94_list = som94['shapeID'].tolist()
som97 = gp.read_file(f'{shpfile_path}1997-0106-SOM.shp')
som97_list = som97['shapeID'].tolist()

dfb_fl1 = dfb_fl1.copy()
dfb_fl1.at[38, 'geob'] = str(ken_list)
dfb_fl1.at[78, 'geob'] = str(som94_list)
dfb_fl1.at[81, 'geob'] = str(som97_list)

dfb_fl1a = dfb_fl1.rename(columns={"geob": "geob_list"})
dfb_fl1a['geob_list'] = dfb_fl1a['geob_list'].apply(lambda x: eval(x) if isinstance(x, str) and x.startswith('[') else x)
dfb_fl_a = pd.concat([dfb_fl2, dfb_fl1a])

def get_adm1_list(my_list):
    if not isinstance(my_list, list):
        try:
            if pd.isna(my_list).any():
                return [], []
        except:
            return [], []
    
    try:
        adm1_list = [value for value in my_list if isinstance(value, str) and 'ADM1' in value]
        adm2_list = [value for value in my_list if isinstance(value, str) and 'ADM2' in value]
        return adm1_list, adm2_list
    except:
        return [], []

aa_list = []
bb_list = []
for idx, row in dfb_fl_a.iterrows():
    aa, bb = get_adm1_list(row['geob_list'])
    aa_list.append(aa)
    bb_list.append(bb)

dfb_fl_a['geob_adm2_list'] = bb_list
dfb_fl_a['geob_adm1_list'] = aa_list

dfb_fl_adm1 = dfb_fl_a[['Dis No', 'geob_adm1_list']]
dfb_fl_adm1_a = dfb_fl_adm1[dfb_fl_adm1['geob_adm1_list'].map(lambda d: len(d)) > 0]

def safe_dict_lookup(x, dict_obj):
    try:
        return [dict_obj[i] for i in x]
    except:
        return []

dfb_fl_adm1_a['geob_adm2_list'] = dfb_fl_adm1_a['geob_adm1_list'].apply(
    lambda x: safe_dict_lookup(x, geob_db3_dict)
)

def flatten(l):
    return [item for sublist in l for item in sublist]

aa_list = []
for idx, row in dfb_fl_adm1_a.iterrows():
    aa = flatten(row['geob_adm2_list'])
    aa_list.append(aa)

dfb_fl_adm1_a['geob_adm2_list_a'] = aa_list
dfb_fl_adm1_b = dfb_fl_adm1_a[['Dis No', 'geob_adm2_list_a']]

dfb_fl2 = pd.merge(dfb_fl_a, dfb_fl_adm1_b, on='Dis No', how='left')
dfb_fl2['geob_adm2_list_a'] = dfb_fl2['geob_adm2_list_a'].apply(lambda d: d if isinstance(d, list) else [])
dfb_fl2['geob_adm2_list_a'] = (dfb_fl2.geob_adm2_list + dfb_fl2.geob_adm2_list_a).map(set).map(list)

dfb_fl_part3 = dfb_fl2[['Dis No', 'geob_adm2_list_a']]
dfb_fl_part3.columns = ['Dis No', 'geob_adm2_list']

2025-02-13 13:32:21,731 - INFO - NumExpr defaulting to 8 threads.
<ipython-input-24-9a7d8bcc24a6>:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_adm1_a['geob_adm2_list'] = dfb_fl_adm1_a['geob_adm1_list'].apply(
<ipython-input-24-9a7d8bcc24a6>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_adm1_a['geob_adm2_list_a'] = aa_list

In [25]:
dfb_parts=pd.concat([dfb_fl_part1,dfb_fl_part2,dfb_fl_part3],axis=0)
dfb_parts1=dfb_parts.drop_duplicates('Dis No')

In [26]:
df=dfb_parts.groupby('Dis No').agg({'geob_adm2_list': 'sum'})

In [27]:
df_a=df[df['geob_adm2_list'].map(lambda d: len(d)) > 0]
adisno=df_a.index.tolist()

In [28]:
#df.to_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/test.csv')

In [29]:
dfb_fl_ea1=dfb_fl_ea[~dfb_fl_ea['Dis No'].isin(adisno)]
df1=dfb_fl_ea1[['Dis No','Location']]
df1
#df1.to_csv('/home/bulbul/Documents/07-2022/impact_weather_icpac/lab/ea_climada/ea-ibf-climada/impact_catalog/fl_part4_missing_location.csv')

             Dis No                                           Location
33    1993-0503-DJI                                      Djibouti City
41    1990-0582-ETH                                     Gambela region
44    1990-0352-KEN                                                NaN
125   1993-0519-ETH                                   Near Addis Abeba
126   1993-0520-ETH                             Gollam, Gonder regions
155   1990-0016-TZA                              Lindi, Mtwara, Masasi
158   1990-0018-TZA  Moshi, Rombo districts (Kilimanjaro, Rukwa reg...
209   1993-0143-SDN                                         Port Sudan
474   1996-0473-SOM                                                NaN
684   1999-0351-ETH                                           Iowlands
690   1999-0419-ETH                  Limu District (South Of Ethiopia)
691   1999-0609-ETH                                     Itang District
960   1999-0443-SDN                              Pibor (Jonglei state)
962   1999-0316-SDN                            Sheikh Sherif (Dongola)
4123  2018-0477-RWA                                                NaN
4362  2021-0343-ETH                                                NaN
4470  2020-0188-RWA  Gakenke (Northern province), Nyabihu, Muhangad...
4580  2022-0332-SOM                                  Galkayo district
4622  2022-0445-SDN  Kas District (South Darfur Stat); Kassala, Sou...
4631  2022-0258-TZA                           Mbeya and Songwe Regions

# part4 missing admins
1990-0352-KEN - http://erepository.uonbi.ac.ke/bitstream/handle/11295/66135/Alfred%20Opere.pdf?sequence
    
1996-0473-SOM - https://reliefweb.int/report/somalia/fews-bulletin-july-24-1996
    
2018-0477-RWA - https://reliefweb.int/disaster/fl-2018-000029-rwa
    
2021-0343-ETH - https://floodlist.com/tag/ethiopia

Flood catalogs for EA from 1985

https://drought.unl.edu/archive/Documents/NDMC/Workshops/539/Pres/GHA2_Policelli-floods-1.pdf

In [32]:
import geopandas as gp

_ken=gp.read_file(f'{shpfile_path}1990-0352-KEN.shp')

print(_ken['shapeID'].tolist())

['KEN-ADM2-3_0_0-B3', 'KEN-ADM2-3_0_0-B4', 'KEN-ADM2-3_0_0-B6', 'KEN-ADM2-3_0_0-B7', 'KEN-ADM2-3_0_0-B8', 'KEN-ADM2-3_0_0-B11', 'KEN-ADM2-3_0_0-B12', 'KEN-ADM2-3_0_0-B15', 'KEN-ADM2-3_0_0-B21', 'KEN-ADM2-3_0_0-B24', 'KEN-ADM2-3_0_0-B40', 'KEN-ADM2-3_0_0-B53', 'KEN-ADM2-3_0_0-B55', 'KEN-ADM2-3_0_0-B56', 'KEN-ADM2-3_0_0-B59', 'KEN-ADM2-3_0_0-B62', 'KEN-ADM2-3_0_0-B66', 'KEN-ADM2-3_0_0-B70']

In [34]:
_som=gp.read_file(f'{shpfile_path}1996-0473-SOM.shp')

print(_som['shapeID'].tolist())

['SOM-ADM2-3_0_0-B5', 'SOM-ADM2-3_0_0-B9', 'SOM-ADM2-3_0_0-B10', 'SOM-ADM2-3_0_0-B13', 'SOM-ADM2-3_0_0-B14', 'SOM-ADM2-3_0_0-B15', 'SOM-ADM2-3_0_0-B16', 'SOM-ADM2-3_0_0-B26', 'SOM-ADM2-3_0_0-B30', 'SOM-ADM2-3_0_0-B33', 'SOM-ADM2-3_0_0-B38', 'SOM-ADM2-3_0_0-B41', 'SOM-ADM2-3_0_0-B43', 'SOM-ADM2-3_0_0-B45', 'SOM-ADM2-3_0_0-B50', 'SOM-ADM2-3_0_0-B53', 'SOM-ADM2-3_0_0-B61', 'SOM-ADM2-3_0_0-B62', 'SOM-ADM2-3_0_0-B65', 'SOM-ADM2-3_0_0-B69']

In [35]:
_ken1=gp.read_file(f'{shpfile_path}1996-0474-KEN.shp')

print(_ken1['shapeID'].tolist())

['KEN-ADM2-3_0_0-B8', 'KEN-ADM2-3_0_0-B11', 'KEN-ADM2-3_0_0-B12', 'KEN-ADM2-3_0_0-B24', 'KEN-ADM2-3_0_0-B40', 'KEN-ADM2-3_0_0-B49', 'KEN-ADM2-3_0_0-B53', 'KEN-ADM2-3_0_0-B56', 'KEN-ADM2-3_0_0-B62']

## part4 repalce

In [41]:
import pandas as pd
import geopandas as gp


geob_db=gp.read_file(f'data/ea_adm2_geoboundaries_adm1_code.shp')
#https://stackoverflow.com/a/54137935/2501953
geob_db1=geob_db[['adm1_shape','shapeID']]
#geob_db2=geob_db1.set_index('adm1_shape')
#geob_db_dict=geob_db1['adm1_shape'].groupby(level=0).apply(lambda x: x.to_dict('shapeID')).to_dict()
geob_db2=geob_db1.groupby('adm1_shape').agg({'shapeID':lambda x: list(x)})
geob_db3=geob_db2.reset_index()
geob_db3.columns=['gaul_adm1_geob','shapeID']
geob_db3_dict = dict(zip(geob_db3.gaul_adm1_geob, geob_db3.shapeID))


dfb_fl=pd.read_csv(f'data/fl_part4_missing_location_v1.csv')



dfb_fl1=dfb_fl[dfb_fl['geob'].notna()]
dfb_fl1['geob_list']=dfb_fl1['geob'].str.split(',').replace(' ','')



def get_adm1_list(my_list):
    keys = ['ADM1','ADM2']
    aa=[[value for value in my_list if key in value] for key in set(keys)][0]
    bb=[[value for value in my_list if key in value] for key in set(keys)][1]
    #if not aa:
    #    bb=['']
    #else:
    #    bb=aa
    return aa,bb


aa_list=[]
bb_list=[]
for idx,row in dfb_fl1.iterrows():
    #dfb_dr1.loc[idx,'geob_adm2_list'] = get_adm1_list(row['geob_list'])
    aa,bb=get_adm1_list(row['geob_list'])
    #dfb_dr1.loc[idx,'geob_adm2_list'] =aa
    #print(aa)
    aa_list.append(aa)
    bb_list.append(bb)

dfb_fl1['geob_adm2_list']=bb_list
dfb_fl1['geob_adm1_list']=aa_list


# dfb_dr1['geob_adm2'] = dfb_dr1['geob_list'].apply(lambda x: [geob_db3_dict[i] for i in x])
dfb_fl_adm1=dfb_fl1[['Dis No','geob_adm1_list']]
#dfb_dr1_adm1_a=dfb_dr1_adm1[dfb_dr1_adm1['geob_adm1_list'].notna()]
dfb_fl_adm1_a=dfb_fl_adm1[dfb_fl_adm1['geob_adm1_list'].map(lambda d: len(d)) > 0]
dfb_fl_adm1_a['geob_adm2_list'] = dfb_fl_adm1_a['geob_adm1_list'].apply(lambda x: [geob_db3_dict[i] for i in x if i in geob_db3_dict])

def flatten(l):
    return [item for sublist in l for item in sublist]

aa_list=[]
for idx,row in dfb_fl_adm1_a.iterrows():
    aa=flatten(row['geob_adm2_list'])
    aa_list.append(aa)
    #dfb_dr1_adm1_a.loc[idx,'geob_adm2_list_a'] = flatten(row['geob_adm2_list'])
    
dfb_fl_adm1_a['geob_adm2_list_a']=aa_list

dfb_fl_adm1_b=dfb_fl_adm1_a[['Dis No','geob_adm2_list_a']]

dfb_fl2=pd.merge(dfb_fl1,dfb_fl_adm1_b,on='Dis No',how='left')

dfb_fl2['geob_adm2_list_a'] = dfb_fl2['geob_adm2_list_a'].apply(lambda d: d if isinstance(d, list) else [])

dfb_fl2['geob_adm2_list_a']=(dfb_fl2.geob_adm2_list+dfb_fl2.geob_adm2_list_a).map(set).map(list)

dfb_fl_part4=dfb_fl2[['Dis No','geob_adm2_list_a']]

dfb_fl_part4.columns=['Dis No','geob_adm2_list']

<ipython-input-41-aa649507b867>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_adm1_a['geob_adm2_list'] = dfb_fl_adm1_a['geob_adm1_list'].apply(lambda x: [geob_db3_dict[i] for i in x if i in geob_db3_dict])
<ipython-input-41-aa649507b867>:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfb_fl_adm1_a['geob_adm2_list_a']=aa_list

In [42]:
dfb_fl_part4

           Dis No                                     geob_adm2_list
0   1993-0503-DJI                                                 []
1   1990-0582-ETH                                [ETH-ADM1-3_0_0-B6]
2   1990-0352-KEN                                                 []
3   1993-0519-ETH                                [ETH-ADM1-3_0_0-B1]
4   1993-0520-ETH                                                 []
5   1990-0016-TZA            [TZA-ADM1-3_0_0-B11, TZA-ADM1-3_0_0-B8]
6   1990-0018-TZA                                                 []
7   1993-0143-SDN                                                 []
8   1993-0005-TZA                                                 []
9   1993-0157-TZA                                                 []
10  1994-0013-TZA                                                 []
11  1996-0474-KEN                                                 []
12  1997-0328-ETH                                                 []
13  1995-0317-SOM                                                 []
14  1996-0473-SOM                                                 []
15  1997-0049-TZA                                                 []
16  1998-0096-TZA                                                 []
17  1999-0351-ETH                                [ETH-ADM1-3_0_0-B6]
18  1999-0419-ETH                                [ETH-ADM1-3_0_0-B8]
19  1999-0316-SDN                                                 []
20  1999-0407-SDN                                                 []
21  2018-0477-RWA                                                 []
22  2021-0343-ETH                                [ETH-ADM1-3_0_0-B1]
23  2020-0188-RWA                                                 []
24  2022-0332-SOM                                                 []
25  2022-0445-SDN  [SDN-ADM1-3_0_0-B15, SDN-ADM1-3_0_0-B2, SDN-AD...
26  2022-0258-TZA                                [TZA-ADM1-3_0_0-B6]

In [43]:
dfb_parts=pd.concat([dfb_fl_part1,dfb_fl_part2,dfb_fl_part3,dfb_fl_part4],axis=0)
#dfb_parts1=dfb_parts.drop_duplicates('Dis No')
df=dfb_parts.groupby('Dis No').agg({'geob_adm2_list': 'sum'})
df['len_of_list'] = df.geob_adm2_list.agg([len])
df['geob_adm2_list1'] = df['geob_adm2_list'].apply(lambda x: list(set(x)))
#df['len_of_list1'] = df.geob_un.agg([len])
df1=df[['geob_adm2_list1']]
df2=df1.reset_index()
df2.columns=['Dis No','geob_adm2_list']
df2.to_excel("em_dat_ea_flood_adm2_v0.xlsx",index=False)

In [44]:
df2

            Dis No                                     geob_adm2_list
0    1990-0016-TZA            [TZA-ADM1-3_0_0-B11, TZA-ADM1-3_0_0-B8]
1    1990-0018-TZA                                                 []
2    1990-0352-KEN                                                 []
3    1990-0582-ETH                                [ETH-ADM1-3_0_0-B6]
4    1993-0005-TZA           [TZA-ADM2-3_0_0-B30, TZA-ADM2-3_0_0-B13]
..             ...                                                ...
264  2022-0055-RWA  [RWA-ADM2-3_0_0-B7, RWA-ADM2-3_0_0-B15, RWA-AD...
265  2022-0232-RWA  [RWA-ADM2-3_0_0-B26, RWA-ADM2-3_0_0-B30, RWA-A...
266  2022-0258-TZA                                [TZA-ADM1-3_0_0-B6]
267  2022-0332-SOM                                                 []
268  2022-0445-SDN  [SDN-ADM1-3_0_0-B15, SDN-ADM1-3_0_0-B3, SDN-AD...

[269 rows x 2 columns]